FROM python:3.10.6-buster

COPY pyproject.toml pyproject.toml
COPY models models
COPY solution/fastapi solution/fastapi
COPY Makefile Makefile

RUN make install_amd64

CMD uvicorn solution.fastapi.fastapi:app --host 0.0.0.0 --port $PORT
